#ifndef MACRO_H
#define MACRO_H

#define MAX_BUFFER_SIZE 4096
#define MAX_EPOLL_EVENTS 500
#define FDSIZE 1000
#define BACKLOG 5

#define CLIENT_PREPARED 1
#define RSA_PUBKEY_RCVD 2
#define SERVER_PREPARED 3
#define RSA_PUBKEY_SENT 4
#define DES_KEY_RCVD 5

#define INVALID_OPTION 1
#define SUCCESS 0
#define CREATE_SOCKET_ERROR -1
#define CONNECT_ERROR -2
#define GET_LOCAL_ADDRESS_ERROR -3
#define CREATE_PIPE_ERROR -4
#define EPOLL_CREATE_ERROR -5
#define READ_ERROR -5
#define BIND_SOCKET_ERROR -6
#define SET_AFTER_STARTED -7
#define MESSAGE_SENT_ERROR -8
#define DES_KEY_SENT_ERROR -9
#define SET_REUSEADDR_ERROR -10
#define LISTEN_ERROR -11
#define ACCEPT_ERROR -12
#define NO_CORR_FD_CLIENT_ERROR -13
#define RSA_PUBKEY_SENT_ERROR -14
#define CLIENT_NOT_CONNECT_ERROR -15

#endif
